<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-03P7KFF" ignored="0" name="All" tests="6" failures="3" timestamp="11 Dec 2019 05:02:00 GMT" time="0.525" errors="0">
  <testcase name="test1" time="0.04" classname="tests.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at tests.LoginTest.test1(LoginTest.java:10)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.001" classname="tests.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at tests.LoginTest.test2(LoginTest.java:15)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="tests.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at tests.LoginTest.test3(LoginTest.java:21)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test10" time="0.0" classname="tests.SignOutTest">
    <skipped/>
  </testcase> <!-- test10 -->
  <testcase name="test20" time="0.001" classname="tests.SignOutTest"/>
  <testcase name="test30" time="0.001" classname="tests.SignOutTest"/>
</testsuite> <!-- All -->
